// flow-typed signature: f9483aa4260f8a0a5c2a752f1e99efe5
// flow-typed version: <<STUB>>/alpha-scripts_v~2.0.5-beta/flow_v0.117.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'alpha-scripts'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'alpha-scripts' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'alpha-scripts/bin/alpha-scripts' {
  declare module.exports: any;
}

declare module 'alpha-scripts/config/buildInfo' {
  declare module.exports: any;
}

declare module 'alpha-scripts/config/env' {
  declare module.exports: any;
}

declare module 'alpha-scripts/config/InjectGitInfoPlugin' {
  declare module.exports: any;
}

declare module 'alpha-scripts/config/jest/babelTransform' {
  declare module.exports: any;
}

declare module 'alpha-scripts/config/jest/cssTransform' {
  declare module.exports: any;
}

declare module 'alpha-scripts/config/jest/fileTransform' {
  declare module.exports: any;
}

declare module 'alpha-scripts/config/paths' {
  declare module.exports: any;
}

declare module 'alpha-scripts/config/polyfills' {
  declare module.exports: any;
}

declare module 'alpha-scripts/config/webpack.config' {
  declare module.exports: any;
}

declare module 'alpha-scripts/config/webpackDevServer.config' {
  declare module.exports: any;
}

declare module 'alpha-scripts/scripts/build' {
  declare module.exports: any;
}

declare module 'alpha-scripts/scripts/start' {
  declare module.exports: any;
}

declare module 'alpha-scripts/scripts/test' {
  declare module.exports: any;
}

declare module 'alpha-scripts/scripts/utils/createJestConfig' {
  declare module.exports: any;
}

// Filename aliases
declare module 'alpha-scripts/bin/alpha-scripts.js' {
  declare module.exports: $Exports<'alpha-scripts/bin/alpha-scripts'>;
}
declare module 'alpha-scripts/config/buildInfo.js' {
  declare module.exports: $Exports<'alpha-scripts/config/buildInfo'>;
}
declare module 'alpha-scripts/config/env.js' {
  declare module.exports: $Exports<'alpha-scripts/config/env'>;
}
declare module 'alpha-scripts/config/InjectGitInfoPlugin.js' {
  declare module.exports: $Exports<'alpha-scripts/config/InjectGitInfoPlugin'>;
}
declare module 'alpha-scripts/config/jest/babelTransform.js' {
  declare module.exports: $Exports<'alpha-scripts/config/jest/babelTransform'>;
}
declare module 'alpha-scripts/config/jest/cssTransform.js' {
  declare module.exports: $Exports<'alpha-scripts/config/jest/cssTransform'>;
}
declare module 'alpha-scripts/config/jest/fileTransform.js' {
  declare module.exports: $Exports<'alpha-scripts/config/jest/fileTransform'>;
}
declare module 'alpha-scripts/config/paths.js' {
  declare module.exports: $Exports<'alpha-scripts/config/paths'>;
}
declare module 'alpha-scripts/config/polyfills.js' {
  declare module.exports: $Exports<'alpha-scripts/config/polyfills'>;
}
declare module 'alpha-scripts/config/webpack.config.js' {
  declare module.exports: $Exports<'alpha-scripts/config/webpack.config'>;
}
declare module 'alpha-scripts/config/webpackDevServer.config.js' {
  declare module.exports: $Exports<'alpha-scripts/config/webpackDevServer.config'>;
}
declare module 'alpha-scripts/scripts/build.js' {
  declare module.exports: $Exports<'alpha-scripts/scripts/build'>;
}
declare module 'alpha-scripts/scripts/start.js' {
  declare module.exports: $Exports<'alpha-scripts/scripts/start'>;
}
declare module 'alpha-scripts/scripts/test.js' {
  declare module.exports: $Exports<'alpha-scripts/scripts/test'>;
}
declare module 'alpha-scripts/scripts/utils/createJestConfig.js' {
  declare module.exports: $Exports<'alpha-scripts/scripts/utils/createJestConfig'>;
}
