// flow-typed signature: 5b7e63f1904abb559c61534f2404b7ef
// flow-typed version: <<STUB>>/redux-devtools-maintained_v~3.6.0/flow_v0.117.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-devtools-maintained'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-devtools-maintained' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-devtools-maintained/lib/createDevTools' {
  declare module.exports: any;
}

declare module 'redux-devtools-maintained/lib' {
  declare module.exports: any;
}

declare module 'redux-devtools-maintained/lib/persistState' {
  declare module.exports: any;
}

declare module 'redux-devtools-maintained/src/createDevTools' {
  declare module.exports: any;
}

declare module 'redux-devtools-maintained/src' {
  declare module.exports: any;
}

declare module 'redux-devtools-maintained/src/persistState' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-devtools-maintained/lib/createDevTools.js' {
  declare module.exports: $Exports<'redux-devtools-maintained/lib/createDevTools'>;
}
declare module 'redux-devtools-maintained/lib/index' {
  declare module.exports: $Exports<'redux-devtools-maintained/lib'>;
}
declare module 'redux-devtools-maintained/lib/index.js' {
  declare module.exports: $Exports<'redux-devtools-maintained/lib'>;
}
declare module 'redux-devtools-maintained/lib/persistState.js' {
  declare module.exports: $Exports<'redux-devtools-maintained/lib/persistState'>;
}
declare module 'redux-devtools-maintained/src/createDevTools.js' {
  declare module.exports: $Exports<'redux-devtools-maintained/src/createDevTools'>;
}
declare module 'redux-devtools-maintained/src/index' {
  declare module.exports: $Exports<'redux-devtools-maintained/src'>;
}
declare module 'redux-devtools-maintained/src/index.js' {
  declare module.exports: $Exports<'redux-devtools-maintained/src'>;
}
declare module 'redux-devtools-maintained/src/persistState.js' {
  declare module.exports: $Exports<'redux-devtools-maintained/src/persistState'>;
}
